### ISSUE TITLE
Implement token parsing

### ISSUE THREAD

**Issue by lsmoura** [mtgjson/mtgjson4_temporary#8]
Tokens should be retrieved and inserted on a given set file. It will not be downloaded and parsed one-by-one like cards are now.

Tokens reside here: https://github.com/Cockatrice/Magic-Token/blob/master/tokens.xml

**Comment by Psithief** [comment]
I can't stop you, but I can warn you of the pitfalls.

## Usage Notes:
1. If the picture URL is from `magiccards.info` or `media.wizards.com` then it was actually printed by WotC.  
   That rule is only applicable to permanents and emblems. (Neither site has a version of the experience counter or energy reserve that I know of.)
2. Any <name> that ends with (token) is such because it conflicts with a pre-existing card name. _Most_ of these are from cards in Future Sight.
3. Tokens stopped having 'haste' printed _by itself_ in their text boxes soon after tokens were commonplace (Tenth Edition). Therefore, a `1/1 red elemental` from Shadowmoor has not been included in this list.
4. There has been no attempt to use data from Vanguard, Unhinged or Unglued.
5. This file also includes reminder cards `Morph` and `Manifest`.
6. Sets with different art variants of the same card are probably not represented consistently.

**Comment by Psithief** [comment]
I cleaned up the data a bit.
https://github.com/Cockatrice/Magic-Token/commit/e7dca0075b578e991bba2f810e79897dd2d2e0d4

**Comment by lsmoura** [comment]
Module `xml2js` added to package.json for token parsing.

**Comment by lsmoura** [comment]
This is also done.
